### ISSUE TITLE
if its an sqrt it shouldn't ask for the second number

### ISSUE THREAD

**Issue by Vano2903** [Fraaaaaunimib/Unimib#2]
either you ask for the power of the root or if you use a sqrt don't ask for the second number

**Comment by fraaaaa4** [comment]
Me being as lazy as a fish:

I should change the number2 stuff, gotta move it down where case(): is.

(I'm lazy)

**Comment by fraaaaa4** [comment]
Fixed! Now, the program will ask you for a first number, then, depending on the operation you want to do, it’ll ask you accordingly. 

So, for average it’ll ask you three numbers, for sqrt it’ll ask nothing the second time, and for the other ones only two numbers.
